$(function(){
	$(".spoiler").next(".hide").hide();
	$(".spoiler").click(function(){
		if($(this).next(".hide:first").css("display")=="none"){
			$(this).addClass("u");
			$(this).next(".hide:first").slideDown();
		}else{
			$(this).removeClass("u");
			$(this).next(".hide:first").slideUp();
		}
	});
});